"""Initial migration

Revision ID: 821fb61f60ce
Revises: 
Create Date: 2025-06-11 10:24:28.193209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '821fb61f60ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students')
    # ### end Alembic commands ###
